platzigram/platzigram/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# Views
from users import views as users_views

# Para poder visualizar las imgs durante desarrollo se agrega el mas y la linea
# Ademas se deben cambiar la mediaurl y media root en settings
urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    # Users
    path('users/', include(('users.urls', 'users'), namespace='users')),    
    # Posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/posts/urls.py
"""Posts URLs"""

# Django
from django.urls import path
from django.contrib.auth.decorators import login_required

# Views
from posts import views


urlpatterns = [
    path(
        route='',
        view=login_required(views.PostFeedView.as_view()),
        name='feed'
    ),

    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create_post'
    ),

    path(
        route='posts/<int:post_id>/',
        view=login_required(views.PostDetailView.as_view()),
        name='detail'
    ),
]

platzigram/users/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.contrib.auth.decorators import login_required

# Views
from users import views

urlpatterns = [

    # Management
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
    ),

    # Posts
    path(
        route='<str:username_slug>/',
        view=login_required(views.UserDetailView.as_view()),
        name='detail'
    ),
]

platzigram/users/models.py
# User models

# Django
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Profile(models.Model):
    """
    Profile model

    Proxy Model that extends the base data with other information.
    """
    # Relation con la tabla user
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Campos extendidos
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    # time
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username"""
        return self.user.username

platzigram/users/forms.py
"""Users Forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    """Signup form"""

    # Por default los valores son requeridos
    username = forms.CharField(
        min_length=5,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Username','class': 'form-control'})
    )
    password = forms.CharField(
        min_length=8,
        max_length=70,
        widget=forms.PasswordInput(attrs={'placeholder': 'Password','class': 'form-control'})
    )
    password_confirmation = forms.CharField(
        min_length=8,
        max_length=70,
        widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirmation','class': 'form-control'})
    )
    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'First name','class': 'form-control'})
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Last name','class': 'form-control'})
    )
    email = forms.CharField(
        min_length=7,
        max_length=70,
        widget=forms.EmailInput(attrs={'placeholder': 'Email','class': 'form-control'})
    )

    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

platzigram/users/views.py
"""User views."""

# Django
from django.contrib.auth import logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth.models import User

# Forms
from users.forms import SignupForm

# Models
from posts.models import Post
from users.models import Profile

# Create your views here.


class SignupView(FormView):
    """Signup View."""
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """If the form is valid save the user"""
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    """Login view"""
    template_name = 'users/login.html'
    redirect_authenticated_user = True

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout View."""

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update a user's profile view"""
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']
    # Return success url
    def get_object(self):
        """Return user's profile"""
        return self.request.user.profile
    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username_slug': username})


class UserDetailView(DetailView):
    """User detail view."""
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username_slug'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(profile__user=user).order_by('-created')
        return context

platzigram/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5 border-info rounded" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mt-2 mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>
    
    <!--JS libraries-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

platzigram/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" max-width="150px" height="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update_profile" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url "posts:detail" post.id %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

platzigram/templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Login - Platzigram</title>
{% endblock head_content %}

{% block container %}
	{% if form.errors %}
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			<p>Your username and password didn't match. Please try again.</p>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	{% if message %}
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			{{message}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	<form method="POST" action="{% url 'users:login' %}">
		{% csrf_token %}
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Username" name="username">
		</div>
		<div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name="password">
		</div>

		<button type="submit" class="btn btn-outline-info btn-block mt-5"><i class="lead">Sign in!</i></button>	
	</form>
	<div class="mx-auto mt-1" style="width: 300px;">
		<p>Not registered? <a href="{% url "users:signup" %}">Create an account</a></p>
	</div>
{% endblock container %}

platzigram/templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Signup - Platzigram</title>
{% endblock head_content %}
{% block container %}
	{% if form.errors %}
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			{{form.errors}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	{% if message %}
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			{{message}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	<form method="POST" action="{% url 'users:signup' %}">
		{% csrf_token %}
		{% for input in form %}
			<div class="form-group">
				{{input}}
			</div>
            <div class="invalid-feedback">
                {% for error in input.errors %}{{ error }}{% endfor %}
            </div>
		{% endfor %}

		<button type="submit" class="btn btn-outline-success btn-block mt-5"><i class="lead">Register!</i></button>	
	</form>
		<div class="mx-auto mt-1" style="width: 300px;">
		<p>Already registered? <a href="{% url "users:login" %}">Sign In</a></p>
	</div>
{% endblock container %}

platzigram/templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ user.username }} - Platzigram </title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if user.profile.picture %}
                        <img src="{{ user.profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture" ></p>
                    </div>
                </div>
                {% for error in form.picture.errors %}
                	<div class="alert alert-danger"><b>Picture:</b> {{error}}</div>
                {% endfor %}

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control 
                        {% if form.website.errors %}
                        	is-invalid
                        {% endif %}"
                        type="text"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors %}{{form.website.value}}{% else %}{{ user.profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                    	{% for error in form.website.errors %}
                    		{{error}}
                    	{% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                    	class="form-control 
                        {% if form.biography.errors %}
                        	is-invalid
                        {% endif %}" 
                    	name="biography">{% if form.errors %}{{form.biography.value}}{% else %}{{user.profile.biography }}{% endif %}</textarea>
                	<div class="invalid-feedback">{% for error in form.biography.errors %}{{error}}{% endfor %}</div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control 
                        {% if form.phone_number.errors %}
                        	is-invalid
                        {% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{ user.profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                    	{% for error in form.phone_number.errors %}
                    		{{error}}
                    	{% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}